version: '3.7'
services:
  mongo:
    image: mongo:3.6
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test
    links:
      - mongo 
    depends_on: 
      - mongo 
    volumes:
      - .:/starter
      - /starter/node_modules
    # command: ["npm", "run", "web"]
    command: ["npm", "run", "web.dev"]
  worker:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test
      - JOB_TYPES=photos
    links:
      - mongo 
    depends_on: 
      - mongo 
    volumes:
      - .:/starter
      - /starter/node_modules
    # command: ["npm", "run", "worker"]
    command: ["npm", "run", "worker.dev"]